# Generated by Django 4.2 on 2023-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=250)),
                ("phone", models.CharField(max_length=12)),
                ("salary", models.IntegerField()),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
            ],
        ),
    ]
