# Generated by Django 4.2 on 2023-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userlogin",
            fields=[
                (
                    "userid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
