# Generated by Django 4.2 on 2023-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Grade_Card",
            fields=[
                ("Roll_No", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Physics", models.IntegerField()),
                ("Chemistry", models.IntegerField()),
                ("Maths", models.IntegerField()),
                ("English", models.IntegerField()),
                ("Computer_Science", models.IntegerField()),
            ],
        ),
    ]
