# Generated by Django 4.2 on 2023-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=50)),
                ("Phone_No", models.IntegerField()),
                ("DOB", models.DateField()),
                ("Gender", models.CharField(max_length=6)),
            ],
        ),
    ]
